version: '3'
services:
  db:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=xrt
      - POSTGRES_PASSWORD=xrt
      - POSTGRES_DB=xrt-db
    volumes:
      - xrt-db:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  xrt-db: