version: '3'
services:
  db:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=xrt
      - POSTGRES_PASSWORD=xrt
      - POSTGRES_DB=xrt-db
    volumes:
      - xrt-db:/var/lib/postgresql/data/
    ports:
      - 5433:5432

  redis:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning --requirepass xrt
      volumes:
        - xrt-redis:/data

volumes:
  xrt-db:
  xrt-redis: